#!/bin/bash

# Get brightness value
brightness="$(xbacklight -get | awk -F. '{print $1}')"

# Display brightness icon depending on brightness level
if [ "$brightness" -gt "75" ]; then
        icon=""
elif [ "$brightness" -gt "35" ]; then
        icon=""
elif [ "$brightness" -gt "0" ]; then
        icon=""
else
        echo  && exit
fi

# Output icon and brightness
echo "$icon $brightness%"
