#!/bin/sh

# Get CPU temperature
temp="$(sensors | awk '/^Package/ {print $4}')"

# Set temperature icon
icon=糖

# Define mouse controls
case $BUTTON in
	# Left-click shows a notification with CPU temperature
	1) notify-send "CPU temperature: " "$icon$temp" ;;
	# Right-click opens a terminal instance with sensors
	3) setsid -f "$TERMINAL" -e sensors ;;
esac

# Show icon and temperature value
echo "$icon$temp"
