#!/bin/sh

# Get CPU temperature
temp="$(sensors | awk '/^Package/ {print $4}')"

# Set temperature icon
icon=糖

# Define mouse controls
case $BUTTON in
	# Left-click opens a terminal instance with sensors
	1) setsid -f "$TERMINAL" -e sensors ;;
	# Right-click shows a notification with CPU temperature
	3) notify-send "CPU temperature: " "$icon$temp" ;;
esac

# Show icon and temperature value
echo "$icon $temp"
