#!/bin/bash

# Get CPU usage
usage="$(mpstat | awk 'NR==4 {print $4}')"

# CPU icon
icon=

# Define mouse controls
case $BUTTON in
	# Left-click creates a notification with cpu usage percentage
	1) notify-send "CPU usage: " "$icon $usage%" ;;
	# Right-click opens a terminal instance running htop
	3) setsid -f "$TERMINAL" -e htop ;;
esac

echo "$icon $usage%"
