#!/bin/bash

memory="$(free -h | awk '/^Mem/ {print $3"/"$2}' | sed s/i//g)"
icon=

#Define mouse controls
case $BUTTON in
	# Right-click shows a notification with memory level
	3) notify-send "Memory: " "$icon $memory" ;;
esac

# Output icon and memory stats
echo "$icon $memory"
