#!/bin/bash

memory="$(free -h | awk '/^Mem/ {print $3"/"$2}' | sed s/i//g)"
icon=

#Define mouse controls
case $BUTTON in
	# Left-click shows a notification with memory level
	1) notify-send "Memory: " "$memory" ;;
esac

# Output icon and memory stats
echo "$icon $memory"
