#!/bin/bash

time="$(date '+%b %d (%a) %I:%M%p')"
icon=

# Define mouse controls
case $BUTTON in
	# Left-click opens an instance of gsimplecal
	1) gsimplecal ;;
	# Right-click shows a notification with current time
	3) notify-send "Current time: " "$icon $time" ;;
esac

echo "$icon $time"
