#!/bin/sh

# Get CPU count
cpuCount="$(grep processor /proc/cpuinfo | wc -l)"

# Counter for creating variables to store all CPU's frequencies
c=1

# Get frequencies for all found cores
for (( core = 1; core <= $cpuCount; core++ ))
do
	eval "Core$c="$(grep MHz /proc/cpuinfo | awk -v a=$core 'NR == a {print $4}' | cut -d "." -f 1)"";
	c=$((c+1));
done

# Display icon
icon=

# Define mouse controls
case $BUTTON in
	# Left-click opens up a terminal showing frequency of all cores
	1) setsid -f "$TERMINAL" -e watch grep MHz /proc/cpuinfo ;;
	# Right-click shows a notification with all the found CPU's frequencies
	3) notify-send "Frequency" "CPU0: $Core1\nCPU1: $Core2\nCPU2: $Core3\nCPU3: $Core4"
esac

# Display CPU icon and frequency
echo "$icon $Core1 MHz"
