#!/bin/sh

# Grab each processor's frequency
core1="$(grep MHz /proc/cpuinfo | awk 'NR == 1 {print $4}' | cut -d "." -f 1)"
core2="$(grep MHz /proc/cpuinfo | awk 'NR == 2 {print $4}' | cut -d "." -f 1)"
core3="$(grep MHz /proc/cpuinfo | awk 'NR == 3 {print $4}' | cut -d "." -f 1)"
core4="$(grep MHz /proc/cpuinfo | awk 'NR == 4 {print $4}' | cut -d "." -f 1)"

# Display icon
icon=

# Define mouse controls
case $BUTTON in
	# Left-click opens up a terminal showing frequency of all cores
	1) setsid -f "$TERMINAL" -e watch grep MHz /proc/cpuinfo ;;
	# Right-click shows a notification with all the found cpu's frequencies
	3) notify-send "Frequency" "CPU0:$core1\nCPU1:$core2\nCPU2:$core3\nCPU3:$core4"
esac

# Display CPU icon and frequency
echo "$icon $core1 MHz"
