#!/bin/sh

# Get CPU temperature
package="$(sensors | awk '/^Package/ {print $4}')"
core0="$(sensors | awk '/^Core 0/ {print $3}')"
core1="$(sensors | awk '/^Core 1/ {print $3}')"

# Set temperature icon
icon=糖

# Define mouse controls
case $BUTTON in
	# Left-click opens a terminal instance with sensors
	1) setsid -f "$TERMINAL" -e watch sensors ;;
	# Right-click shows a notification with CPU temperature
	3) notify-send "CPU temperature " "Package: $package\nCore 0: $core0\nCore 1: $core1" ;;
esac

# Show icon and temperature value
echo "$icon $package"
