#!/bin/bash

# Grab volume percentage value from amixer
vol="$(pamixer --get-volume)"

# Display sound icon depending on volume
if [ "$vol" -gt "75" ]; then
	icon="墳"
elif [ "$vol" -gt "35" ]; then
	icon="奔"
elif [ "$vol" -gt "0" ]; then
	icon="奄"
else
	echo "ﱝ  0%" && exit
fi

# Define mouse controls
case $BUTTON in
	# Left-click shows a notification with volume level
	1) notify-send "Volume: " "$icon" "$vol%" ;;
	# Right-click opens pavucontrol instance
	3) pavucontrol ;;
esac

# Output icon and volume
echo "$icon $vol%"
